"""
TrustLayer EU — AI Content Classifier
MVP Component 2

Classifies images/media for synthetic content using:
  - Pixel-level statistical features (DCT entropy, noise floor, compression artefacts)
  - C2PA manifest check (provenance credential present / absent / stripped)
  - SynthID watermark flag (simulated — in production calls Gemini API)
  - Ensemble confidence score combining all signals

Reproduces the HK deepfake fraud use-case scenario.
Output: verdict dict with confidence score, label, and escalation flag.
"""

import hashlib
import math
import os
import random
import time
from datetime import datetime, timezone
from io import BytesIO


# ── Feature extraction (no heavy model needed for MVP demo) ──────────────────
# In production this would be a HuggingFace vision model fine-tuned on
# FaceForensics++ / DFDC dataset. Here we use interpretable image statistics
# that genuinely differ between authentic and synthetic images.

def extract_pixel_features(image_bytes: bytes) -> dict:
    """
    Extract statistical features from raw image bytes that correlate with
    synthetic content (without requiring a GPU model).
    
    Real forensic signals used by production detectors:
      - DCT coefficient entropy (AI images are too smooth → lower entropy)
      - High-frequency noise floor (GAN images lack natural sensor noise)
      - Compression artefact pattern (AI images compress differently)
      - Colour channel correlation (deepfakes often have channel imbalance)
    """
    # Use byte distribution as proxy for image statistics
    byte_array = list(image_bytes[:8192])  # sample first 8KB
    
    if not byte_array:
        return {"error": "empty_file"}

    # Entropy of byte distribution (Shannon entropy)
    freq = {}
    for b in byte_array:
        freq[b] = freq.get(b, 0) + 1
    total = len(byte_array)
    entropy = -sum((c/total) * math.log2(c/total) for c in freq.values())
    
    # High-frequency component proxy (variance of byte deltas)
    deltas = [abs(byte_array[i+1] - byte_array[i]) for i in range(len(byte_array)-1)]
    hf_variance = sum(d**2 for d in deltas) / len(deltas) if deltas else 0
    
    # Byte range utilisation (synthetic images often have narrower ranges)
    byte_range = max(byte_array) - min(byte_array)
    
    # Mean absolute deviation
    mean_val = sum(byte_array) / total
    mad = sum(abs(b - mean_val) for b in byte_array) / total

    return {
        "byte_entropy":    round(entropy, 4),
        "hf_variance":     round(hf_variance, 2),
        "byte_range":      byte_range,
        "mean_abs_dev":    round(mad, 2),
        "sample_size":     total,
    }


def score_pixel_features(features: dict) -> float:
    """
    Convert pixel features into a synthetic_probability score (0–100).
    Higher score = more likely synthetic.
    
    Thresholds derived from FaceForensics++ literature:
      - Low entropy (<6.5) → AI images tend to be smoother
      - Low HF variance (<1000) → lack of natural sensor noise
      - Narrow byte range (<180) → compressed colour palette
    """
    if "error" in features:
        return 50.0  # uncertain

    score = 0.0

    # Entropy signal (weight: 35%)
    entropy = features["byte_entropy"]
    if entropy < 5.5:
        score += 35
    elif entropy < 6.5:
        score += 20
    elif entropy < 7.0:
        score += 10
    else:
        score += 0

    # HF variance signal (weight: 30%)
    hf = features["hf_variance"]
    if hf < 500:
        score += 30
    elif hf < 1500:
        score += 15
    elif hf < 3000:
        score += 5
    else:
        score += 0

    # Byte range signal (weight: 20%)
    br = features["byte_range"]
    if br < 150:
        score += 20
    elif br < 200:
        score += 10
    elif br < 230:
        score += 5
    else:
        score += 0

    # MAD signal (weight: 15%)
    mad = features["mean_abs_dev"]
    if mad < 40:
        score += 15
    elif mad < 60:
        score += 8
    elif mad < 80:
        score += 3
    else:
        score += 0

    return round(score, 1)


# ── C2PA provenance check ─────────────────────────────────────────────────────
def check_c2pa(image_bytes: bytes, filename: str = "") -> dict:
    """
    Check for C2PA Content Credentials in the file.
    
    In production: parse XMP/JUMBF metadata blocks.
    Here: simulate based on filename hints or random (for demo).
    
    Returns:
      status: "present" | "absent" | "stripped"
      detail: what the credential says (if present)
    """
    # Simulate: files named *_ai* or *synthetic* have C2PA credentials
    fn = filename.lower()
    if any(k in fn for k in ["ai", "synthetic", "generated", "deepfake", "fake"]):
        return {
            "status": "present",
            "generator": "OpenAI Media Service",
            "edited_with_ai": True,
            "detail": "C2PA Content Credentials found. Media fully generated by AI and subsequently edited with AI tools.",
            "credential_hash": "0x" + hashlib.sha256(image_bytes[:256]).hexdigest()[:16]
        }
    elif any(k in fn for k in ["stripped", "no_meta", "scrubbed"]):
        return {
            "status": "stripped",
            "generator": None,
            "edited_with_ai": None,
            "detail": "C2PA metadata appears to have been removed. Absence of watermark does NOT prove non-AI origin.",
            "credential_hash": None
        }
    else:
        # For unknown files: check byte signature (JUMBF box magic bytes: 6A756D62)
        hex_header = image_bytes[:512].hex()
        has_jumbf = "6a756d62" in hex_header
        if has_jumbf:
            return {
                "status": "present",
                "generator": "Unknown AI provider",
                "edited_with_ai": True,
                "detail": "C2PA JUMBF manifest detected in file metadata.",
                "credential_hash": "0x" + hashlib.sha256(image_bytes[:256]).hexdigest()[:16]
            }
        return {
            "status": "absent",
            "generator": None,
            "edited_with_ai": None,
            "detail": "No C2PA credentials found. Content may be authentic, created by non-C2PA AI, or metadata was stripped.",
            "credential_hash": None
        }


# ── SynthID watermark check (simulated) ───────────────────────────────────────
def check_synthid(image_bytes: bytes, filename: str = "") -> dict:
    """
    Simulate SynthID Google DeepMind watermark detection.
    In production: call Gemini API with image and ask 'verify using synthid'.
    
    Returns: detected (bool), confidence (float), detail (str)
    """
    fn = filename.lower()
    if any(k in fn for k in ["synthid", "gemini", "google", "ai", "generated"]):
        return {
            "detected": True,
            "confidence": round(random.uniform(0.82, 0.97), 3),
            "detail": "SynthID watermark signal detected. Consistent with Google AI generation.",
            "note": "Production: verified via Gemini App 'verify using synthid' feature (requires signed-in account)."
        }
    return {
        "detected": False,
        "confidence": round(random.uniform(0.05, 0.25), 3),
        "detail": "No SynthID watermark detected. May be authentic, non-Google AI, or watermark removed.",
        "note": "Absence of SynthID does NOT confirm authenticity — content could be from other AI systems."
    }


# ── Ensemble scorer ───────────────────────────────────────────────────────────
def ensemble_score(pixel_score: float, c2pa: dict, synthid: dict) -> float:
    """
    Combine three signals into a final synthetic_probability (0–100).
    
    Weights:
      Pixel features : 40%
      C2PA credential: 40%
      SynthID         : 20%
    """
    # C2PA component
    if c2pa["status"] == "present":
        c2pa_score = 90.0
    elif c2pa["status"] == "stripped":
        c2pa_score = 55.0   # suspicious but uncertain
    else:
        c2pa_score = 20.0   # absent = slightly less likely but not conclusive

    # SynthID component
    synthid_score = synthid["confidence"] * 100 if synthid["detected"] else synthid["confidence"] * 30

    final = (pixel_score * 0.40) + (c2pa_score * 0.40) + (synthid_score * 0.20)
    return round(min(final, 100.0), 1)


# ── Label and escalation ──────────────────────────────────────────────────────
def classify(synthetic_prob: float) -> tuple:
    """
    Return (label, action, confidence_in_verdict).
    
    < 30   → LIKELY AUTHENTIC   → AUTO_PASS
    30–70  → INCONCLUSIVE       → ESCALATE TO HUMAN
    > 70   → LIKELY SYNTHETIC   → CIRCUIT_BREAK / block action
    """
    if synthetic_prob < 30:
        return (
            "LIKELY AUTHENTIC",
            "AUTO_PASS",
            round(100 - synthetic_prob, 1),
            "Low synthetic probability. Proceed with normal workflow."
        )
    elif synthetic_prob <= 70:
        return (
            "INCONCLUSIVE",
            "ESCALATE_TO_HUMAN",
            round(100 - abs(synthetic_prob - 50) * 2, 1),
            "Ambiguous signals. Human review required before authorising any high-value action."
        )
    else:
        return (
            "LIKELY SYNTHETIC",
            "CIRCUIT_BREAK",
            round(synthetic_prob, 1),
            "High synthetic probability. Block action, escalate to human review and out-of-band verification."
        )


# ── Evidence hash ─────────────────────────────────────────────────────────────
def build_evidence_hash(image_bytes, result):
    import json
    payload = json.dumps({
        "file_hash": hashlib.sha256(image_bytes).hexdigest(),
        "label": result["label"],
        "synthetic_prob": result["synthetic_probability"],
        "action": result["action"],
        "ts": result["timestamp"]
    }, sort_keys=True)
    return "0x" + hashlib.sha256(payload.encode()).hexdigest()


# ── Main public function ───────────────────────────────────────────────────────
def classify_content(image_bytes: bytes, filename: str = "upload.jpg") -> dict:
    """
    Full content classification pipeline.
    Returns structured result dict for Flask API.
    """
    t0 = time.time()

    features  = extract_pixel_features(image_bytes)
    px_score  = score_pixel_features(features)
    c2pa      = check_c2pa(image_bytes, filename)
    synthid   = check_synthid(image_bytes, filename)
    synth_prob = ensemble_score(px_score, c2pa, synthid)
    label, action, confidence, message = classify(synth_prob)

    result = {
        "pipeline": "ai_content_classifier",
        "filename": filename,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "elapsed_ms": round((time.time() - t0) * 1000, 1),
        "file_size_bytes": len(image_bytes),
        "file_hash": "0x" + hashlib.sha256(image_bytes).hexdigest(),
        "pixel_features": features,
        "pixel_synthetic_score": px_score,
        "c2pa": c2pa,
        "synthid": synthid,
        "synthetic_probability": synth_prob,
        "label": label,
        "confidence_score": confidence,
        "action": action,
        "message": message,
        "escalate_to_human": action in ("ESCALATE_TO_HUMAN", "CIRCUIT_BREAK"),
        "layer_path": (
            "Data → AI → Consensus (auto-pass)"
            if action == "AUTO_PASS"
            else "Data → AI → Human Layer → Consensus"
        )
    }

    result["evidence_hash"] = build_evidence_hash(image_bytes, result)
    return result


# ── CLI demo ──────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\n" + "="*60)
    print("  TrustLayer EU — AI Content Classifier Demo")
    print("="*60)

    # Scenario 1: Authentic image (random bytes with high entropy)
    print("\n[SCENARIO 1] Authentic photograph")
    print("-"*60)
    authentic_bytes = bytes([random.randint(0, 255) for _ in range(4096)])
    r1 = classify_content(authentic_bytes, "family_photo.jpg")
    print(f"  Label           : {r1['label']}")
    print(f"  Action          : {r1['action']}")
    print(f"  Synthetic prob  : {r1['synthetic_probability']}%")
    print(f"  Confidence      : {r1['confidence_score']}%")
    print(f"  C2PA status     : {r1['c2pa']['status']}")
    print(f"  SynthID         : {'detected' if r1['synthid']['detected'] else 'not detected'}")
    print(f"  Message         : {r1['message']}")
    print(f"  Layer path      : {r1['layer_path']}")

    # Scenario 2: HK deepfake fraud — AI-generated corporate video call
    print("\n[SCENARIO 2] HK deepfake fraud — AI-generated corporate video call")
    print("-"*60)
    # Simulate smooth AI-generated image bytes (lower entropy, narrower range)
    ai_bytes = bytes([random.randint(80, 180) for _ in range(4096)])
    r2 = classify_content(ai_bytes, "corporate_videocall_ai_generated.jpg")
    print(f"  Label           : {r2['label']}")
    print(f"  Action          : {r2['action']}")
    print(f"  Synthetic prob  : {r2['synthetic_probability']}%")
    print(f"  Confidence      : {r2['confidence_score']}%")
    print(f"  C2PA status     : {r2['c2pa']['status']}")
    print(f"  C2PA detail     : {r2['c2pa']['detail']}")
    print(f"  SynthID         : {'detected' if r2['synthid']['detected'] else 'not detected'}")
    print(f"  Escalate human  : {r2['escalate_to_human']}")
    print(f"  Evidence hash   : {r2['evidence_hash'][:20]}...")
    print(f"  Layer path      : {r2['layer_path']}")

    # Scenario 3: Stripped metadata (suspicious)
    print("\n[SCENARIO 3] Stripped metadata — provenance removed")
    print("-"*60)
    stripped_bytes = bytes([random.randint(60, 200) for _ in range(4096)])
    r3 = classify_content(stripped_bytes, "document_stripped.jpg")
    print(f"  Label           : {r3['label']}")
    print(f"  Action          : {r3['action']}")
    print(f"  Synthetic prob  : {r3['synthetic_probability']}%")
    print(f"  C2PA status     : {r3['c2pa']['status']}")
    print(f"  C2PA detail     : {r3['c2pa']['detail']}")
    print(f"  Message         : {r3['message']}")
    print()
